language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "2.7"

env:
  - DJANGO="django==1.8.15"

matrix:
  include:
    - python: "3.5"
      env: DJANGO="django==1.9.10"

install:
  - pip install $DJANGO
  - pip install -e .
  - pip install flake8

before_script:
  - flake8 --exclude=migrations --ignore=E501,E225,E128,E126,F401,F403 pages
  - cd pages/tests

script: python runtests.py
