language: python

python:
  - "3.3"
  - "3.4"
  - "2.7"

env:
  - DJANGO="django==1.8.3"
  - DJANGO="django==1.7.9"
  - DJANGO="django==1.6.11"

install:
  - pip install $DJANGO
  - pip install -e .
  - pip install flake8

before_script:
  - flake8 --exclude=south_migrations,migrations --ignore=E501,E225,E128,E126,F401,F403 pages
  - cd pages/tests

script: python runtests.py
