# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markitup.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ptype', models.CharField(default='page', max_length=64, verbose_name='Type')),
                ('template', models.CharField(blank=True, max_length=254)),
                ('comment', models.TextField(blank=True, max_length=254)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated')),
                ('date_approved', models.DateTimeField(blank=True, null=True, verbose_name='Approved')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Publication date')),
                ('date_publication_end', models.DateTimeField(blank=True, null=True, verbose_name='Publication end date')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Draft')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('is_login_required', models.BooleanField(default=False, verbose_name='Login required')),
                ('is_permission_required', models.BooleanField(default=False, verbose_name='Permission required')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['tree_id', 'lft'],
                'permissions': (('view_page', 'Can view pages'),),
                'get_latest_by': 'date_publication',
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
            },
        ),
        migrations.CreateModel(
            name='PageContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('class_name', models.CharField(max_length=100, verbose_name='Class')),
                ('admin_class_name', models.CharField(max_length=100, verbose_name='Admin Class')),
                ('is_extended', models.BooleanField(default=False, verbose_name='Extended')),
            ],
            options={
                'verbose_name': 'Content Type',
                'verbose_name_plural': 'Content Types',
            },
        ),
        migrations.CreateModel(
            name='PageDefaultContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('content_types', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name': 'Default Content',
                'verbose_name_plural': 'Default Content',
            },
        ),
        migrations.CreateModel(
            name='PageGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'verbose_name': 'Page Group Permissions',
                'verbose_name_plural': 'Pages Groups Permissions',
            },
        ),
        migrations.CreateModel(
            name='PageMarkdownContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=100, verbose_name='Type')),
                ('language', models.CharField(default='en', max_length=5)),
                ('sid', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('is_extended', models.BooleanField(default=False, verbose_name='Extended?')),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated')),
                ('text', markitup.fields.MarkupField(blank=True, no_rendered_field=True)),
                ('is_template', models.BooleanField(default=False, verbose_name='Template?')),
                ('_text_rendered', models.TextField(blank=True, editable=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages_pagemarkdowncontent_creator', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Page')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages_pagemarkdowncontent_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Markdown',
                'verbose_name_plural': 'Markdown',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageMetaContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=100, verbose_name='Type')),
                ('language', models.CharField(default='en', max_length=5)),
                ('sid', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('is_extended', models.BooleanField(default=False, verbose_name='Extended?')),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated')),
                ('title', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True, max_length=160)),
                ('keywords', models.CharField(blank=True, max_length=200)),
                ('is_noindex', models.BooleanField(default=False, verbose_name='NoIndex')),
                ('is_nofollow', models.BooleanField(default=False, verbose_name='NoFollow')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages_pagemetacontent_creator', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Page')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages_pagemetacontent_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Meta',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageRedirectContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=100, verbose_name='Type')),
                ('language', models.CharField(default='en', max_length=5)),
                ('sid', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('is_extended', models.BooleanField(default=False, verbose_name='Extended?')),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated')),
                ('redirect_to_page', models.CharField(blank=True, max_length=254, null=True)),
                ('redirect_to_url', models.URLField(blank=True, max_length=254, null=True)),
                ('is_permanent', models.BooleanField(default=False, verbose_name='Permanent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages_pageredirectcontent_creator', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Page')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages_pageredirectcontent_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Redirect',
                'verbose_name_plural': 'Redirect',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageSlugContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=100, verbose_name='Type')),
                ('language', models.CharField(default='en', max_length=5)),
                ('sid', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('is_extended', models.BooleanField(default=False, verbose_name='Extended?')),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated')),
                ('slug', models.CharField(max_length=245)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages_pageslugcontent_creator', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Page')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages_pageslugcontent_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Slug',
                'verbose_name_plural': 'Slugs',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageTextContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=100, verbose_name='Type')),
                ('language', models.CharField(default='en', max_length=5)),
                ('sid', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, unique=True)),
                ('is_extended', models.BooleanField(default=False, verbose_name='Extended?')),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated')),
                ('text', models.TextField(blank=True)),
                ('is_template', models.BooleanField(default=False, verbose_name='Template?')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages_pagetextcontent_creator', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Page')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages_pagetextcontent_editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Text',
                'verbose_name_plural': 'Text',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page User Permissions',
                'verbose_name_plural': 'Pages Users Permissions',
            },
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.PageContentType'),
        ),
        migrations.AddField(
            model_name='page',
            name='default_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_default_content', to='pages.PageDefaultContent'),
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.Page'),
        ),
        migrations.AddField(
            model_name='page',
            name='sites',
            field=models.ManyToManyField(help_text='The site(s) where this pages is accessible.', to='sites.Site', verbose_name='sites'),
        ),
        migrations.AddField(
            model_name='page',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pageslugcontent',
            unique_together=set([('language', 'page')]),
        ),
        migrations.AlterUniqueTogether(
            name='pagemetacontent',
            unique_together=set([('language', 'page')]),
        ),
        migrations.AlterUniqueTogether(
            name='pagecontent',
            unique_together=set([('page', 'type')]),
        ),
    ]
